#!/usr/bin/env bash
# T013: Generate CDC Payload - Create realistic CDC envelope format test messages
# Part of Feature 003: Kafka Performance Validation
# [P] Can run in parallel with other tasks

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESULTS_DIR="$SCRIPT_DIR/../results"
OUTPUT_FILE="${1:-$RESULTS_DIR/cdc-test-payload.json}"
NUM_MESSAGES="${2:-100}"

echo "========================================="
echo "CDC Payload Generator"
echo "========================================="
echo "Output File: $OUTPUT_FILE"
echo "Number of Messages: $NUM_MESSAGES"
echo "========================================="

# Generate CDC envelope format payload (Debezium structure)
generate_cdc_message() {
  local op="${1:-c}"  # c=create, u=update, d=delete, r=read
  local comment_id="test-$(uuidgen | tr '[:upper:]' '[:lower:]')"
  local video_id="mcY4M9gjtsI"
  local timestamp_ms=$(($(date +%s) * 1000))

  cat <<EOF
{
  "payload": {
    "before": null,
    "after": {
      "comment_id": "$comment_id",
      "video_id": "$video_id",
      "channel_id": "UCX6OQ3DkcsbYNE6H8uQQuVA",
      "comment_text": "This is a test CDC message generated by the performance validation suite.",
      "likes": 42,
      "replies": 3,
      "published_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
      "sentiment_label": "positive",
      "country_code": "US",
      "updated_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    },
    "op": "$op",
    "source": {
      "version": "2.5.0.Final",
      "connector": "postgresql",
      "name": "dbserver",
      "ts_ms": $timestamp_ms,
      "snapshot": "false",
      "db": "app",
      "sequence": "[null,\"12345678\"]",
      "schema": "public",
      "table": "comments",
      "txId": 12345,
      "lsn": 12345678,
      "xmin": null
    },
    "ts_ms": $timestamp_ms,
    "transaction": null
  }
}
EOF
}

# Generate multiple messages
echo "[1/2] Generating $NUM_MESSAGES CDC messages..."
> "$OUTPUT_FILE"  # Clear file

for ((i=1; i<=NUM_MESSAGES; i++)); do
  # Randomly select operation type (mostly creates, some updates)
  if [[ $((i % 10)) == 0 ]]; then
    OP="u"  # 10% updates
  else
    OP="c"  # 90% creates
  fi

  generate_cdc_message "$OP" >> "$OUTPUT_FILE"

  # Progress indicator every 25 messages
  if [[ $((i % 25)) == 0 ]]; then
    echo "  Generated $i/$NUM_MESSAGES messages..."
  fi
done

# Calculate file size
FILE_SIZE=$(du -h "$OUTPUT_FILE" | awk '{print $1}')
AVG_MSG_SIZE=$(wc -c < "$OUTPUT_FILE")
AVG_MSG_SIZE=$((AVG_MSG_SIZE / NUM_MESSAGES))

echo "[2/2] Generation complete"
echo ""
echo "========================================="
echo "CDC PAYLOAD GENERATION RESULTS"
echo "========================================="
echo "Total Messages: $NUM_MESSAGES"
echo "Output File: $OUTPUT_FILE"
echo "File Size: $FILE_SIZE"
echo "Average Message Size: ${AVG_MSG_SIZE} bytes"
echo "========================================="

# Display sample message
echo ""
echo "Sample CDC Message (first record):"
echo "-----------------------------------"
head -n 30 "$OUTPUT_FILE"
echo "..."

exit 0
